name: Behave Systems Tests CI

on:
  push
  
jobs:
  RunBehaveTests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install chromedriver
        uses: nanasess/setup-chromedriver@master
      - name: Install behave
        run: pip install behave behave-webdriver
      - name: test isitchristmas
        working-directory: isitchrsitmas
        run: behave
      - name: test peppers-ghost
        working-directory: peppers-ghost
        run: behave
